export const MEASURES = {
  diabetic_eye_exam: {
    key: 'diabetic_eye_exam',
    name: 'Diabetic Eye Exam',
    code: 'EED / C07',
    hedisSpec: 'Retinal eye exam in last 24 months for diabetic patients (18-75).',
    cutpoints: { '3star': 65, '4star': 75, '5star': 85 },
    weight: 1,
    statusCol: 'diabetic_eye_exam_status',
    valueCol: 'last_exam_date',
    valueLabel: 'Last Exam Date',
  },
  blood_pressure_control: {
    key: 'blood_pressure_control',
    name: 'Blood Pressure Control',
    code: 'CBP / C11',
    hedisSpec: 'Systolic < 140 and Diastolic < 90 mmHg for hypertensive members (18-85).',
    cutpoints: { '3star': 68, '4star': 78, '5star': 88 },
    weight: 3,
    statusCol: 'blood_pressure_control_status',
    valueCol: 'last_bp_reading',
    valueLabel: 'Last BP Reading',
  },
  diabetes_med_adherence: {
    key: 'diabetes_med_adherence',
    name: 'Diabetes Med Adherence',
    code: 'PDC / D11',
    hedisSpec: 'Proportion of Days Covered (PDC) >= 80% for diabetic medications.',
    cutpoints: { '3star': 78, '4star': 84, '5star': 90 },
    weight: 1,
    statusCol: 'diabetes_med_adherence_status',
    valueCol: 'adherence_pct',
    valueLabel: 'Adherence %',
  },
  flu_vaccination: {
    key: 'flu_vaccination',
    name: 'Annual Flu Vaccine',
    code: 'AIS-E / C03',
    hedisSpec: 'Flu shot received between July 1 prior year & end of measurement year.',
    cutpoints: { '3star': 68, '4star': 77, '5star': 84 },
    weight: 1,
    statusCol: 'flu_vaccination_status',
    valueCol: 'last_flu_shot_date',
    valueLabel: 'Last Flu Shot Date',
  },
};

export const COLUMNS_CONFIG = [
  { key: 'member_id', label: 'Member ID', sortable: true, width: 'w-36' },
  { key: 'member_name', label: 'Member Name', sortable: true, width: 'w-44' },
  { key: 'age', label: 'Age', sortable: true, width: 'w-16' },
  { key: 'gender', label: 'Gender', sortable: true, width: 'w-16' },
  { key: 'city', label: 'City', sortable: true, width: 'w-32' },
  { key: 'state', label: 'State', sortable: true, width: 'w-32' },
  { key: 'insurance_company', label: 'Insurance', sortable: true, width: 'w-28' },
  { key: 'has_diabetes', label: 'Diabetes', sortable: true, width: 'w-20' },
  { key: 'has_hypertension', label: 'Hypertension', sortable: true, width: 'w-24' },
  { key: 'diabetic_eye_exam_status', label: 'Eye Exam Status', sortable: true, width: 'w-32' },
  { key: 'last_exam_date', label: 'Last Exam Date', sortable: true, width: 'w-32' },
  { key: 'blood_pressure_control_status', label: 'BP Control Status', sortable: true, width: 'w-32' },
  { key: 'last_bp_reading', label: 'Last BP Reading', sortable: true, width: 'w-32' },
  { key: 'diabetes_med_adherence_status', label: 'Med Adherence Status', sortable: true, width: 'w-36' },
  { key: 'adherence_pct', label: 'Adherence %', sortable: true, width: 'w-28' },
  { key: 'flu_vaccination_status', label: 'Flu Vaccine Status', sortable: true, width: 'w-32' },
  { key: 'last_flu_shot_date', label: 'Last Flu Shot Date', sortable: true, width: 'w-32' },
  { key: 'priorityScore', label: 'Priority Score', sortable: true, width: 'w-24' },
];
